### ISSUE TITLE
Gather resourceMonitor's localized translations from the add-on translation system

### ISSUE THREAD

**Issue by cary-rowen** [kefaslungu/resourceMonitor#21]
Hi @kefaslungu 

As the title says, the new version of the add-on adds 9 translatable strings, it might be nice if you could push these translation strings to the add-on translation system and collect translations periodically.
If you are not familiar with this process, you may be able to seek help at groups.io, @josephsl or @nvdaes may also give you some help.

Thanks

**Comment by josephsl** [comment]
Hi all,

I do need to send a pull request for this repo soon, and before doing so, I might be able to take care of localization data exchange if Kefas wants me to.

Thanks.

**Comment by kefaslungu** [comment]
Hi joseph,You can go ahead please. But I have one more request.I don’t quite understand how NVDA does localization. Can you please update the addons documentation?Thanks.  From: Joseph LeeSent: 19 September 2023 15:58To: kefaslungu/resourceMonitorCc: Kefas Lungu; MentionSubject: Re: [kefaslungu/resourceMonitor] Gather resourceMonitor's localized translations from the add-on translation system (Issue #21) Hi all,I do need to send a pull request for this repo soon, and before doing so, I might be able to take care of localization data exchange if Kefas wants me to.Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by josephsl** [comment]
Hi,

For reference, the process is:

1. Add a remote to https://github.com/nvdaaddons/resourceMonitor.
2. Merge the stable branch from the nvdaaddons repository to either stable or main branch, say once a week or two.
3. If working with stable branch in step 2, after merging nvdaaddons repo data, merge stable to main.
4. Merge main to stable.
5. Push merged stable to nvdaaddons stable branch.

Do note that not all add-on authors use this workflow and Subversion-based localization work is about to change (based on words from NV Access and contributors). I will go ahead and relase 23.09 with lcalization data and issue 22 resolution, along with setting last tested version to 2024.1 in the process (the full impact of 2024.1 manifest change won't take effect until psutil and Pythonare upgraded.

Thanks.
